import './sass/main.scss';
import './js/searchByKeyword';
import './js/pagination.js';
import './js/about.js';
import './js/header.js';
import './js/renderPopularFilm.js';
import './js/modal-film.js';
import './js/spinner';
import './js/watchedQueueBtns';
